package com.gt.api.bean.session;

import java.io.Serializable;
import java.util.Date;

/**
 * Created by Administrator on 2017/9/11 0011.
 */
public class Member implements Serializable {
    /**
     *
     */
    private static final long serialVersionUID = 2520956702713776574L;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.df_member_id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer dfMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.public_id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer publicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.fans_currency
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Double fansCurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.flow
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer flow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.integral
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer integral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.level
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.openid
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.phone
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.sex
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.province
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.city
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.country
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.headimgurl
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String headimgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.operate_type
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.mc_id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer mcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.totalMoney
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Double totalmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.totalIntegral
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer totalintegral;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.address
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.email
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.cardId
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String cardid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.cardImgback
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String cardimgback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.cardImg
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String cardimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.birth
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Date birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.currencyDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Date currencydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.flowDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Date flowdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.integralDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Date integraldate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.shareCount
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Integer sharecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.shareDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Date sharedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.remark
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.cardChecked
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private Byte cardchecked;

    private Byte isbuy;


    private boolean isPass=false;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.name
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String name;



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.nickname
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    private String nickname;


    private String scenceCode;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.busId
     *
     * @mbggenerated Tue Dec 13 15:57:54 CST 2016
     */
    private Integer busid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.pwd
     *
     * @mbggenerated Tue Dec 13 15:57:54 CST 2016
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.loginMode
     *
     * @mbggenerated Tue Dec 13 15:57:54 CST 2016
     */
    private Byte loginmode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_wx_bus_member.oldId
     *
     * @mbggenerated Tue Dec 13 15:57:54 CST 2016
     */
    private String oldid;

    private String openid2;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.id
     *
     * @return the value of t_wx_bus_member.id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     *
     */


    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.id
     *
     * @param id the value for t_wx_bus_member.id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.df_member_id
     *
     * @return the value of t_wx_bus_member.df_member_id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Integer getDfMemberId() {
        return dfMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.df_member_id
     *
     * @param dfMemberId the value for t_wx_bus_member.df_member_id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setDfMemberId(Integer dfMemberId) {
        this.dfMemberId = dfMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.public_id
     *
     * @return the value of t_wx_bus_member.public_id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Integer getPublicId() {
        return publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.public_id
     *
     * @param publicId the value for t_wx_bus_member.public_id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setPublicId(Integer publicId) {
        this.publicId = publicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.fans_currency
     *
     * @return the value of t_wx_bus_member.fans_currency
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Double getFansCurrency() {
        return fansCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.fans_currency
     *
     * @param fansCurrency the value for t_wx_bus_member.fans_currency
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setFansCurrency(Double fansCurrency) {
        this.fansCurrency = fansCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.flow
     *
     * @return the value of t_wx_bus_member.flow
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Integer getFlow() {
        return flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.flow
     *
     * @param flow the value for t_wx_bus_member.flow
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setFlow(Integer flow) {
        this.flow = flow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.integral
     *
     * @return the value of t_wx_bus_member.integral
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.integral
     *
     * @param integral the value for t_wx_bus_member.integral
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.level
     *
     * @return the value of t_wx_bus_member.level
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.level
     *
     * @param level the value for t_wx_bus_member.level
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.openid
     *
     * @return the value of t_wx_bus_member.openid
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.openid
     *
     * @param openid the value for t_wx_bus_member.openid
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.phone
     *
     * @return the value of t_wx_bus_member.phone
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.phone
     *
     * @param phone the value for t_wx_bus_member.phone
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.sex
     *
     * @return the value of t_wx_bus_member.sex
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.sex
     *
     * @param sex the value for t_wx_bus_member.sex
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.province
     *
     * @return the value of t_wx_bus_member.province
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.province
     *
     * @param province the value for t_wx_bus_member.province
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.city
     *
     * @return the value of t_wx_bus_member.city
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.city
     *
     * @param city the value for t_wx_bus_member.city
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.country
     *
     * @return the value of t_wx_bus_member.country
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.country
     *
     * @param country the value for t_wx_bus_member.country
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.headimgurl
     *
     * @return the value of t_wx_bus_member.headimgurl
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getHeadimgurl() {
        return headimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.headimgurl
     *
     * @param headimgurl the value for t_wx_bus_member.headimgurl
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl == null ? null : headimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.operate_type
     *
     * @return the value of t_wx_bus_member.operate_type
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.operate_type
     *
     * @param operateType the value for t_wx_bus_member.operate_type
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.mc_id
     *
     * @return the value of t_wx_bus_member.mc_id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Integer getMcId() {
        return mcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.mc_id
     *
     * @param mcId the value for t_wx_bus_member.mc_id
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setMcId(Integer mcId) {
        this.mcId = mcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.totalMoney
     *
     * @return the value of t_wx_bus_member.totalMoney
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Double getTotalmoney() {
        return totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.totalMoney
     *
     * @param totalmoney the value for t_wx_bus_member.totalMoney
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setTotalmoney(Double totalmoney) {
        this.totalmoney = totalmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.totalIntegral
     *
     * @return the value of t_wx_bus_member.totalIntegral
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Integer getTotalintegral() {
        return totalintegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.totalIntegral
     *
     * @param totalintegral the value for t_wx_bus_member.totalIntegral
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setTotalintegral(Integer totalintegral) {
        this.totalintegral = totalintegral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.address
     *
     * @return the value of t_wx_bus_member.address
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.address
     *
     * @param address the value for t_wx_bus_member.address
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.email
     *
     * @return the value of t_wx_bus_member.email
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.email
     *
     * @param email the value for t_wx_bus_member.email
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.cardId
     *
     * @return the value of t_wx_bus_member.cardId
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getCardid() {
        return cardid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.cardId
     *
     * @param cardid the value for t_wx_bus_member.cardId
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setCardid(String cardid) {
        this.cardid = cardid == null ? null : cardid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.cardImgback
     *
     * @return the value of t_wx_bus_member.cardImgback
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getCardimgback() {
        return cardimgback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.cardImgback
     *
     * @param cardimgback the value for t_wx_bus_member.cardImgback
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setCardimgback(String cardimgback) {
        this.cardimgback = cardimgback == null ? null : cardimgback.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.cardImg
     *
     * @return the value of t_wx_bus_member.cardImg
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getCardimg() {
        return cardimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.cardImg
     *
     * @param cardimg the value for t_wx_bus_member.cardImg
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setCardimg(String cardimg) {
        this.cardimg = cardimg == null ? null : cardimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.birth
     *
     * @return the value of t_wx_bus_member.birth
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.birth
     *
     * @param birth the value for t_wx_bus_member.birth
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.currencyDate
     *
     * @return the value of t_wx_bus_member.currencyDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Date getCurrencydate() {
        return currencydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.currencyDate
     *
     * @param currencydate the value for t_wx_bus_member.currencyDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setCurrencydate(Date currencydate) {
        this.currencydate = currencydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.flowDate
     *
     * @return the value of t_wx_bus_member.flowDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Date getFlowdate() {
        return flowdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.flowDate
     *
     * @param flowdate the value for t_wx_bus_member.flowDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setFlowdate(Date flowdate) {
        this.flowdate = flowdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.integralDate
     *
     * @return the value of t_wx_bus_member.integralDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Date getIntegraldate() {
        return integraldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.integralDate
     *
     * @param integraldate the value for t_wx_bus_member.integralDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setIntegraldate(Date integraldate) {
        this.integraldate = integraldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.shareCount
     *
     * @return the value of t_wx_bus_member.shareCount
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Integer getSharecount() {
        return sharecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.shareCount
     *
     * @param sharecount the value for t_wx_bus_member.shareCount
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setSharecount(Integer sharecount) {
        this.sharecount = sharecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.shareDate
     *
     * @return the value of t_wx_bus_member.shareDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Date getSharedate() {
        return sharedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.shareDate
     *
     * @param sharedate the value for t_wx_bus_member.shareDate
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setSharedate(Date sharedate) {
        this.sharedate = sharedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.remark
     *
     * @return the value of t_wx_bus_member.remark
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.remark
     *
     * @param remark the value for t_wx_bus_member.remark
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.cardChecked
     *
     * @return the value of t_wx_bus_member.cardChecked
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public Byte getCardchecked() {
        return cardchecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.cardChecked
     *
     * @param cardchecked the value for t_wx_bus_member.cardChecked
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setCardchecked(Byte cardchecked) {
        this.cardchecked = cardchecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.name
     *
     * @return the value of t_wx_bus_member.name
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.name
     *
     * @param name the value for t_wx_bus_member.name
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_wx_bus_member.nickname
     *
     * @return the value of t_wx_bus_member.nickname
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_wx_bus_member.nickname
     *
     * @param nickname the value for t_wx_bus_member.nickname
     *
     * @mbggenerated Wed Apr 27 18:58:54 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    public boolean isPass() {
        return isPass;
    }

    public void setPass(boolean isPass) {
        this.isPass = isPass;
    }

    public Byte getIsbuy() {
        return isbuy;
    }

    public void setIsbuy(Byte isbuy) {
        this.isbuy = isbuy;
    }

    private Byte issubscribe;

    public Byte getIssubscribe() {
        return issubscribe;
    }

    public void setIssubscribe(Byte issubscribe) {
        this.issubscribe = issubscribe;
    }

    public String getScenceCode() {
        return scenceCode;
    }

    public void setScenceCode(String scenceCode) {
        this.scenceCode = scenceCode;
    }

    public Integer getBusid() {
        return busid;
    }

    public void setBusid(Integer busid) {
        this.busid = busid;
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public Byte getLoginmode() {
        return loginmode;
    }

    public void setLoginmode(Byte loginmode) {
        this.loginmode = loginmode;
    }

    public String getOldid() {
        return oldid;
    }

    public void setOldid(String oldid) {
        this.oldid = oldid;
    }

    public String getOpenid2() {
        return openid2;
    }

    public void setOpenid2(String openid2) {
        this.openid2 = openid2;
    }

    private Date subscribedate;

    public Date getSubscribedate() {
        return subscribedate;
    }

    public void setSubscribedate(Date subscribedate) {
        this.subscribedate = subscribedate;
    }
}
